### ISSUE TITLE
Swift stdlib tool Error

### ISSUE THREAD

**Issue by mattscorte** [a16z/ai#81]
Getting this error "Swift stdlib tool Error"
Task failed with exit 1 signal 0

I've tried resetting my keychain and account, and still getting the issue. 

The build is successful if I run in on an iPhone simulator, but the build fails when I try to use my phone. (iPhone 7 Plus iOS 11.1)

I'm wondering if it's because I just signed up for my developer account. Will wait and see if it's working in the next day.

**Comment by diegodoval** [comment]
If it runs in simulator it's less likely that it has to do with the project itself. It definitely won't have anything to do with the time after signing up for a dev account. 

It could be an issue with contents out of sync in DerivedData. Try closing Xcode, deleting the contents of the folder ~/Library/Developer/Xcode/DerivedData/   (that is, in your home folder) and starting Xcode again. Deleting this folder is fine because it will be recreated as-needed.

**Comment by mattscorte** [comment]
I fixed the issue. I was having a codesign issue. This was the solve:

> 
1. Delete the derived data as others said.
2. Clean the project as others said.
3. Restart the OS <-- This was the key. Only after a reboot it showed the password popup.
4. When the popup shows that says xcode wants password to something, type your login password, and DO NOT PRESS ALLOW, but PRESS ALWAYS ALLOW. <- Important!

> 



https://stackoverflow.com/questions/39932620/device-build-fails-after-upgrading-to-xcode-8

**Comment by mattscorte** [comment]
Now the error is just 

"Code Sign Error" instead of "Swift stdlib tool Error"

**Comment by diegodoval** [comment]
There are usually more details as to what fails when codesigning. Is it on a specific framework?

**Comment by diegodoval** [comment]
I'll close it since there's no new information. Please reopen if there are updates, thanks!
